/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CitySelector: typeof import('./src/components/CitySelector.vue')['default']
    CurrentWeather: typeof import('./src/components/CurrentWeather.vue')['default']
    ForecastList: typeof import('./src/components/ForecastList.vue')['default']
    WeatherBackground: typeof import('./src/components/WeatherBackground.vue')['default']
    WeatherIcon: typeof import('./src/components/WeatherIcon.vue')['default']
  }
}
